from PySide6.QtGui import QPalette, QColor
from PySide6.QtCore import Qt

def arch_palette():
	palette = QPalette()
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.WindowText, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Active, QPalette.Button, brush)
	brush = QColor(60, 66, 96)
	palette.setColor(QPalette.Active, QPalette.Light, brush)
	brush = QColor(50, 55, 80)
	palette.setColor(QPalette.Active, QPalette.Midlight, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Active, QPalette.Dark, brush)
	brush = QColor(26, 29, 42)
	palette.setColor(QPalette.Active, QPalette.Mid, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.Text, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.BrightText, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.ButtonText, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Active, QPalette.Base, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Active, QPalette.Window, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Active, QPalette.Shadow, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Active, QPalette.AlternateBase, brush)
	brush = QColor(255, 255, 220)
	palette.setColor(QPalette.Active, QPalette.ToolTipBase, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Active, QPalette.ToolTipText, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.WindowText, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Inactive, QPalette.Button, brush)
	brush = QColor(60, 66, 96)
	palette.setColor(QPalette.Inactive, QPalette.Light, brush)
	brush = QColor(50, 55, 80)
	palette.setColor(QPalette.Inactive, QPalette.Midlight, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Inactive, QPalette.Dark, brush)
	brush = QColor(26, 29, 42)
	palette.setColor(QPalette.Inactive, QPalette.Mid, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.Text, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.BrightText, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.ButtonText, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Inactive, QPalette.Base, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Inactive, QPalette.Window, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Inactive, QPalette.Shadow, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Inactive, QPalette.AlternateBase, brush)
	brush = QColor(255, 255, 220)
	palette.setColor(QPalette.Inactive, QPalette.ToolTipBase, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Inactive, QPalette.ToolTipText, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Disabled, QPalette.WindowText, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Disabled, QPalette.Button, brush)
	brush = QColor(60, 66, 96)
	palette.setColor(QPalette.Disabled, QPalette.Light, brush)
	brush = QColor(50, 55, 80)
	palette.setColor(QPalette.Disabled, QPalette.Midlight, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Disabled, QPalette.Dark, brush)
	brush = QColor(26, 29, 42)
	palette.setColor(QPalette.Disabled, QPalette.Mid, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Disabled, QPalette.Text, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Disabled, QPalette.BrightText, brush)
	brush = QColor(20, 22, 32)
	palette.setColor(QPalette.Disabled, QPalette.ButtonText, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Disabled, QPalette.Base, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Disabled, QPalette.Window, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Disabled, QPalette.Shadow, brush)
	brush = QColor(40, 44, 64)
	palette.setColor(QPalette.Disabled, QPalette.AlternateBase, brush)
	brush = QColor(255, 255, 220)
	palette.setColor(QPalette.Disabled, QPalette.ToolTipBase, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Disabled, QPalette.ToolTipText, brush)
	return palette

def gwaddon_dark_palette():
	palette = QPalette()
	palette.setColor(QPalette.Window, QColor(70, 70, 70))
	palette.setColor(QPalette.WindowText, Qt.white)
	palette.setColor(QPalette.Base, QColor(30, 30, 30))
	palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
	palette.setColor(QPalette.Light, QColor(120, 120, 120))
	palette.setColor(QPalette.Midlight, QColor(50, 50, 50))
	palette.setColor(QPalette.Dark, QColor(22, 22, 22))
	palette.setColor(QPalette.Mid, QColor(40, 40, 40))
	palette.setColor(QPalette.Shadow, QColor(5, 5, 5))
	palette.setColor(QPalette.ToolTipBase, Qt.white)
	palette.setColor(QPalette.ToolTipText, Qt.white)
	palette.setColor(QPalette.Text, QColor(250, 250, 250))
	palette.setColor(QPalette.Button, QColor(53, 53, 53))
	palette.setColor(QPalette.ButtonText, Qt.white)
	palette.setColor(QPalette.BrightText, Qt.red)
	palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
	palette.setColor(QPalette.HighlightedText, Qt.black)
	palette.setColor(QPalette.PlaceholderText, QColor(85, 85, 85))
	return palette

def simple_dark_palette():
	palette = QPalette()
	palette.setColor(QPalette.Window, QColor(35, 35, 35))
	palette.setColor(QPalette.WindowText, Qt.white)
	palette.setColor(QPalette.Base, QColor(10, 10, 10))
	palette.setColor(QPalette.AlternateBase, QColor(25, 25, 25))
	palette.setColor(QPalette.Light, QColor(70, 70, 70))
	palette.setColor(QPalette.Midlight, QColor(50, 50, 50))
	palette.setColor(QPalette.Dark, QColor(10, 10, 10))
	palette.setColor(QPalette.Mid, QColor(20, 20, 20))
	palette.setColor(QPalette.Shadow, QColor(1, 1, 1))
	palette.setColor(QPalette.ToolTipBase, Qt.white)
	palette.setColor(QPalette.ToolTipText, Qt.white)
	palette.setColor(QPalette.Text, Qt.white)
	palette.setColor(QPalette.Button, QColor(53, 53, 53))
	palette.setColor(QPalette.ButtonText, Qt.white)
	palette.setColor(QPalette.BrightText, Qt.red)
	palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
	palette.setColor(QPalette.HighlightedText, Qt.black)
	return palette

def dark_palette():
	palette = QPalette()
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.WindowText, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Active, QPalette.Button, brush)
	brush = QColor(100, 100, 100)
	palette.setColor(QPalette.Active, QPalette.Light, brush)
	brush = QColor(83, 83, 83)
	palette.setColor(QPalette.Active, QPalette.Midlight, brush)
	brush = QColor(26, 26, 26)
	palette.setColor(QPalette.Active, QPalette.Dark, brush)
	brush = QColor(44, 44, 44)
	palette.setColor(QPalette.Active, QPalette.Mid, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.Text, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.BrightText, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Active, QPalette.ButtonText, brush)
	brush = QColor(29, 29, 29)
	palette.setColor(QPalette.Active, QPalette.Base, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Active, QPalette.Window, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Active, QPalette.Shadow, brush)
	brush = QColor(33, 33, 33)
	palette.setColor(QPalette.Active, QPalette.AlternateBase, brush)
	brush = QColor(255, 255, 220)
	palette.setColor(QPalette.Active, QPalette.ToolTipBase, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Active, QPalette.ToolTipText, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.WindowText, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Inactive, QPalette.Button, brush)
	brush = QColor(100, 100, 100)
	palette.setColor(QPalette.Inactive, QPalette.Light, brush)
	brush = QColor(83, 83, 83)
	palette.setColor(QPalette.Inactive, QPalette.Midlight, brush)
	brush = QColor(26, 26, 26)
	palette.setColor(QPalette.Inactive, QPalette.Dark, brush)
	brush = QColor(44, 44, 44)
	palette.setColor(QPalette.Inactive, QPalette.Mid, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.Text, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.BrightText, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Inactive, QPalette.ButtonText, brush)
	brush = QColor(29, 29, 29)
	palette.setColor(QPalette.Inactive, QPalette.Base, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Inactive, QPalette.Window, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Inactive, QPalette.Shadow, brush)
	brush = QColor(33, 33, 33)
	palette.setColor(QPalette.Inactive, QPalette.AlternateBase, brush)
	brush = QColor(255, 255, 220)
	palette.setColor(QPalette.Inactive, QPalette.ToolTipBase, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Inactive, QPalette.ToolTipText, brush)
	brush = QColor(26, 26, 26)
	palette.setColor(QPalette.Disabled, QPalette.WindowText, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Disabled, QPalette.Button, brush)
	brush = QColor(100, 100, 100)
	palette.setColor(QPalette.Disabled, QPalette.Light, brush)
	brush = QColor(83, 83, 83)
	palette.setColor(QPalette.Disabled, QPalette.Midlight, brush)
	brush = QColor(26, 26, 26)
	palette.setColor(QPalette.Disabled, QPalette.Dark, brush)
	brush = QColor(44, 44, 44)
	palette.setColor(QPalette.Disabled, QPalette.Mid, brush)
	brush = QColor(26, 26, 26)
	palette.setColor(QPalette.Disabled, QPalette.Text, brush)
	brush = QColor(255, 255, 255)
	palette.setColor(QPalette.Disabled, QPalette.BrightText, brush)
	brush = QColor(26, 26, 26)
	palette.setColor(QPalette.Disabled, QPalette.ButtonText, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Disabled, QPalette.Base, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Disabled, QPalette.Window, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Disabled, QPalette.Shadow, brush)
	brush = QColor(67, 67, 67)
	palette.setColor(QPalette.Disabled, QPalette.AlternateBase, brush)
	brush = QColor(255, 255, 220)
	palette.setColor(QPalette.Disabled, QPalette.ToolTipBase, brush)
	brush = QColor(0, 0, 0)
	palette.setColor(QPalette.Disabled, QPalette.ToolTipText, brush)

	return palette

def auto_palette(color = [67, 67, 67]):
	r_c = color[0] 
	r_g = color[1] 
	r_b = color[2] 
	palette = QPalette()

	if r_c > 125 or r_g > 125 or r_b > 125:
		#LIGHT
		colorWindowText   	=	QColor(0, 0, 0)
		colorButton  		=	QColor(r_c, r_g, r_b)
		colorLight 			=	QColor(round(r_c*0.75), round(r_g*0.75), round(r_b*0.75))
		colorMidlight  		=	QColor(round(r_c*0.85), round(r_g*0.85), round(r_b*0.85))
		colorDark  			=	QColor(round(r_c*0.25), round(r_g*0.25), round(r_b*0.25))
		colorMid  			=	QColor(round(r_c*2), round(r_g*2), round(r_b*2))
		colorText  			=	QColor(0, 0, 0)
		colorBrightText  	=	QColor(0, 0, 0)
		colorButtonText  	=	QColor(0, 0, 0)
		colorBase 			=	QColor(round(r_c*1.9), round(r_g*1.9), round(r_b*1.9))
		colorWindow 		=	QColor(r_c, r_g, r_b)
		colorShadow 		=	QColor(255, 255, 255)
		colorAlternateBase 	=	QColor(round(r_c*0.7), round(r_g*0.7), round(r_b*0.7))
		colorToolTipBase 	=	QColor(0, 0, 0)
		colorToolTipText 	=	QColor(255, 255, 255)

	else:
		#DARK
		colorWindowText   	=	QColor(255, 255, 255)
		colorPholderText    =	QColor(round(r_c*1.25), round(r_g*1.25), round(r_b*1.25))
		colorButton  		=	QColor(r_c, r_g, r_b)
		colorLight 			=	QColor(round(r_c*1.5), round(r_g*1.5), round(r_b*1.5))
		colorMidlight  		=	QColor(round(r_c*1.25), round(r_g*1.25), round(r_b*1.25))
		colorDark  			=	QColor(round(r_c*2.5), round(r_g*2.5), round(r_b*2.5))
		colorMid  			=	QColor(round(r_c*0.5), round(r_g*0.5), round(r_b*0.5))
		colorText  			=	QColor(255, 255, 255)
		colorBrightText  	=	QColor(255, 255, 255)
		colorButtonText  	=	QColor(255, 255, 255)
		colorBase 			=	QColor(round(r_c*0.4), round(r_g*0.4), round(r_b*0.4))
		colorWindow 		=	QColor(r_c, r_g, r_b)
		colorShadow 		=	QColor(0, 0, 0)
		colorAlternateBase 	=	QColor(round(r_c*0.7), round(r_g*0.7), round(r_b*0.7))
		colorToolTipBase 	=	QColor(255, 255, 220)
		colorToolTipText 	=	QColor(0, 0, 0)

	for palette_status in [QPalette.Active,QPalette.Inactive,QPalette.Disabled]:
		palette.setColor(palette_status, QPalette.WindowText, colorWindowText)
		palette.setColor(palette_status, QPalette.Button, colorButton)
		palette.setColor(palette_status, QPalette.Light, colorLight)
		palette.setColor(palette_status, QPalette.Midlight, colorMidlight)
		palette.setColor(palette_status, QPalette.Dark, colorDark)
		palette.setColor(palette_status, QPalette.Mid, colorMid)
		palette.setColor(palette_status, QPalette.Text, colorText)
		palette.setColor(palette_status, QPalette.BrightText, colorBrightText)
		palette.setColor(palette_status, QPalette.ButtonText, colorButtonText)
		palette.setColor(palette_status, QPalette.Base, colorBase)
		palette.setColor(palette_status, QPalette.Window, colorWindow)
		palette.setColor(palette_status, QPalette.Shadow, colorShadow)
		palette.setColor(palette_status, QPalette.AlternateBase, colorAlternateBase)
		palette.setColor(palette_status, QPalette.ToolTipBase, colorToolTipBase)
		palette.setColor(palette_status, QPalette.ToolTipText, colorToolTipText)
		palette.setColor(palette_status, QPalette.PlaceholderText, colorPholderText)


	return palette
